version: '3'
services:
  #nginx serves the web app (frontend) as static files and proxy the /api/* requests to backend
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    hostname: 'nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/logs/:/var/log/nginx/
    depends_on:
      - api
    ports:
      - '80:80'

  #api serves the dotnet app (backend) and can be scaled
  api:
    build: ./be
    ports:
      - '5000'
